### ISSUE TITLE
安全漏洞-文件上传

### ISSUE THREAD

**Issue by YDHCUI** [jiawesoft/jiascheduler#4]
此处可上传任意文件 造成命令执行

![图片](https://github.com/user-attachments/assets/c43a7664-d80f-4d43-bed6-cfa9f912495e)

![图片](https://github.com/user-attachments/assets/210a4439-6a3e-4186-9b0f-e0df3e5773e1)

**Comment by iwannay** [comment]
调度平台本身就是允许登录用户上传文件（上传的文件当然可以是执行文件），执行脚本的，调度平台默认信任登录用户，完全体是会有脚本审批动作的，执行用户控制的，但是并不干预脚本执行，最坏就是说用户可以通过脚本关闭系统，删除目录。

如果绕过了登录可以直接上传文件那么就是安全问题，如果不能绕过登录，那就是正常行为。你是直接绕过了登录么？

**Comment by YDHCUI** [comment]
首先，调度平台本身是不应该有执行脚本权限的，只有部署了agent的机器才应该有执行脚本权限。

其次，不用登录。

**Comment by iwannay** [comment]
@YDHCUI 是的，不应该有执行权限，但是考虑到系统本身的特殊性，内网部署，真实用户偏向内部的运维人员和对系统具备控制权限的开发人员，实际专门处理这个这个收益不大。 用户可以选择关闭该权限，或者采用非root用户部署程序

**Comment by iwannay** [comment]
@YDHCUI 未发现可以绕过登录上传，下载，是否可以展示操作流程

**Comment by iwannay** [comment]
现在的主要问题在于开源版本没有加入全流程审计和作业发布审批，以及ws通信也是http的未采用加密。实际上这类系统本身不具备阻止内鬼，或者脚本小子在内部搞破坏的能力，这种破坏是巨大的，只能依赖审计和发布审批流程控制。真实环境的上传一版会接入oss，不会直接落盘服务器。 对于jiascheduler来说，现在最优先的是完成预设功能的开发。如果用户使用了前期版本，需要用户自身保证在安全的网络环境下使用，以及仅授权给内部人员。
